# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

exclude: '/snapshots/'
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
      hooks:
          - id: check-added-large-files
          - id: check-ast
          - id: check-case-conflict
          - id: check-yaml
          - id: check-merge-conflict
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: trailing-whitespace
            exclude: .bumpversion.cfg

    - repo: https://github.com/asottile/pyupgrade
      rev: v2.7.3
      hooks:
          - id: pyupgrade
            args: [--py36-plus]

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.790
      hooks:
          - id: mypy
            exclude: bin/gcpdiag
            args: ['--ignore-missing-imports', '--scripts-are-modules']

    - repo: https://github.com/timothycrosley/isort
      rev: 5.6.4
      hooks:
          - id: isort

    - repo: https://github.com/pre-commit/mirrors-yapf
      rev: v0.30.0
      hooks:
          - id: yapf

    - repo: https://github.com/pycqa/pylint
      rev: pylint-2.7.4
      hooks:
          - id: pylint

    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.44.0
      hooks:
          - id: terraform_fmt
          # disabled because currently getting an error in kokoro:
          # - Failed to instantiate provider "registry.terraform.io/hashicorp/google" to
          # obtain schema: unknown provider "registry.terraform.io/hashicorp/google"
          #- id: terraform_validate

    - repo: local
      hooks:
          - id: gcpdiag-rule-page
            name: Check that there is a page in website for each lint rule
            entry: ./bin/precommit-website-rules-wrapper
            language: script
            files: ^gcpdiag/lint/[^/]+/(bp|warn|err|sec)_.*.py
            exclude: .*_test.py
