name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
      - gh-test
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Hugo build
        uses: docker://us-docker.pkg.dev/gcpdiag-repo/devel/gcpdiag-hugo:0.1
        with:
          args: /bin/sh -c "cd website && hugo build --themesDir=/themes --baseUrl=https://schweikert.github.io/gcpdiag/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/gh-test'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public
